openapi: "3.0.1"
info:
  title: "Argonaut"
  version: v1
servers:
- url: https://localhost:8090/api
  description: Local instance

paths:
  /v1/hello:
    get:
      summary: Say hello to Jargonaut
      operationId: hello
      responses:
        '200':
          description: hello?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    BadRequest:
      description: The request was not understood
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The ID was not found and is unknown to any system.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          description: Milliseconds since the epoch
        message:
          type: string
        type:
          type: string
      required:
      - message
    Hello:
      type: object
      properties:
        message:
          type: string
          description: Greetings!
