openapi: "3.0.1"
info:
  title: "Mr. Anderson"
  version: v1
servers:
- url: https://localhost:8088/api
  description: Local instance
paths:
  /v1/resources/{profile}/{resourceType}/{resourceVersion}:
    get:
      summary: Execute a query for the resource and version
      operationId: queryResourceVersion
      parameters:
      - in: path
        name: profile
        schema:
          type: string
          enum:
          - argonaut
          - dstu2
          - stu3
        required: true
        description: The FHIR specification
      - in: path
        name: resourceType
        schema:
          type: string
          pattern: "[A-Za-z]+"
        required: true
        description: The resource type, e.g. Patient
      - in: path
        name: resourceVersion
        schema:
          type: string
          pattern: "[0-9]+\\.[0-9]+"
        required: true
        description: The CDW resource version, e.g. 1.03
      - in: query
        name: page
        description: Page number
        schema:
          type: integer
          minimum: 1
          default: 1
      - in: query
        name: _count
        description: Records per page
        schema:
          type: integer
          minimum: 0
          maximum: 20
          default: 15
      - in: query
        name: params
        description: Any execute parameters supported by CDW. These vary by resource.
        schema:
          type: object
          additionalProperties:
            type: string
        style: form
        explode: true
      responses:
        '200':
          description: Search results
          content:
            application/xml:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  responses:
    BadRequest:
      description: The request was not understood
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          description: Milliseconds since the epoch
        message:
          type: string
        type:
          type: string
      required:
      - message

